version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 4
    versioning-strategy: increase
    rebase-strategy: auto
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "npm"
    groups:
      npm-safe-updates:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:15"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 2
    rebase-strategy: auto
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions-safe-updates:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 1
    rebase-strategy: auto
    commit-message:
      prefix: "docker"
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker-safe-updates:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
